server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: default
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${JDBC_URL:jdbcurl}
    password: ${JDBC_PASSWORD:jdbcpassword}
    username: ${JDBC_USERNAME:username}
    driverClassName: ${JDBC_DRIVERCLASSNAME:org.h2.Driver}
    hikari:
        minimum-idle: 1
        maximum-pool-size: ${JDBC_POOLSIZE:10}

  h2:
    console:
      enabled: false